apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"grpc-service","env":"demo"},"name":"grpc-apps","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"env":"demo"}},"template":{"metadata":{"labels":{"app":"grpc-service","env":"demo"},"name":"grpc-service-pod"},"spec":{"containers":[{"env":[{"name":"IS_K8S","value":"true"},{"name":"SVCNAME","value":"grpc-app"},{"name":"CLUSTER","value":"default"},{"name":"POD","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}}],"image":"grpc-app:latest","imagePullPolicy":"Always","name":"grpc-service","ports":[{"containerPort":8081},{"containerPort":9091}],"resources":{"limits":{"cpu":"500m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2024-12-08T11:59:15Z"
  generation: 5
  labels:
    app: grpc-service
    env: demo
  name: grpc-apps
  namespace: default
  resourceVersion: "3920"
  uid: ae252d77-6295-46dd-906d-f36f598bf8b8
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      env: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grpc-service
        env: demo
      name: grpc-service-pod
    spec:
      containers:
      - env:
        - name: IS_K8S
          value: "true"
        - name: SVCNAME
          value: grpc-app
        - name: CLUSTER
          value: default
        - name: POD
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: grpc-app:latest
        imagePullPolicy: Never  # Prevents pulling from external registry
        name: grpc-service
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 9091
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-12-08T11:59:27Z"
    lastUpdateTime: "2024-12-08T11:59:27Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2024-12-08T12:27:19Z"
    lastUpdateTime: "2024-12-08T12:27:19Z"
    message: ReplicaSet "grpc-apps-85b869746c" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 5
  replicas: 4
  unavailableReplicas: 4
  updatedReplicas: 3
